<?php
$ContentConfig['txt']=array(
	'background picture'=>'background picture (all pictures from same folder will be used)',
    'interval (ms)'=>'interval (ms)',
    'effect duration (ms)'=>'effect duration (ms)',
    'name of custom easing effect'=>'name of custom easing effect',
    
    
    'just a flexbox column'=>'just a flexbox column',
    'Extra small (<576px) - no style selected'=>'Extra small (<576px) - no style selected',
    'Extra small (<576px) - column width: 1/12'=>'Extra small (<576px) - column width: 1/12',
    'Extra small (<576px) - column width: one sixth'=>'Extra small (<576px) - column width: one sixth',
    'Extra small (<576px) - column width: one fourth'=>'Extra small (<576px) - column width: one fourth',
    'Extra small (<576px) - column width: one third'=>'Extra small (<576px) - column width: one third',
    'Extra small (<576px) - column width: 5/12'=>'Extra small (<576px) - column width: 5/12',
    'Extra small (<576px) - column width: half'=>'Extra small (<576px) - column width: half',
    'Extra small (<576px) - column width: 7/12'=>'Extra small (<576px) - column width: 7/12',
    'Extra small (<576px) - column width: two thirds'=>'Extra small (<576px) - column width: two thirds',
    'Extra small (<576px) - column width: three fourths'=>'Extra small (<576px) - column width: three fourths',
    'Extra small (<576px) - column width: five sixths'=>'Extra small (<576px) - column width: five sixths',
    'Extra small (<576px) - column width: 11/12'=>'Extra small (<576px) - column width: 11/12',
    'Extra small (<576px) - column width: full width'=>'Extra small (<576px) - column width: full width',
    'Extra small (<576px) - column hidden on this device'=>'Extra small (<576px) - column hidden on this device',
    'Extra small (<576px) - column hidden on this device and upwards'=>'Extra small (<576px) - column hidden on this device and upwards',
    
    'Small (>576px) - no style selected'=>'Small (>576px) - no style selected',
    'Small (>576px) - flexbox column'=>'Small (>576px) - flexbox column',
    'Small (>576px) - column width: 1/12'=>'Small (>576px) - column width: 1/12',
    'Small (>576px) - column width: one sixth'=>'Small (>576px) - column width: one sixth',
    'Small (>576px) - column width: one fourth'=>'Small (>576px) - column width: one fourth',
    'Small (>576px) - column width: one third'=>'Small (>576px) - column width: one third',
    'Small (>576px) - column width: 5/12'=>'Small (>576px) - column width: 5/12',
    'Small (>576px) - column width: half'=>'Small (>576px) - column width: half',
    'Small (>576px) - column width: 7/12'=>'Small (>576px) - column width: 7/12',
    'Small (>576px) - column width: two thirds'=>'Small (>576px) - column width: two thirds',
    'Small (>576px) - column width: three fourths'=>'Small (>576px) - column width: three fourths',
    'Small (>576px) - column width: five sixths'=>'Small (>576px) - column width: five sixths',
    'Small (>576px) - column width: 11/12'=>'Small (>576px) - column width: 11/12',
    'Small (>576px) - column width: full width'=>'Small (>576px) - column width: full width',
    'Small (>576px) - column hidden on this device'=>'Small (>576px) - column hidden on this device',
    'Small (>576px) - column hidden on this device and upwards'=>'Small (>576px) - column hidden on this device and upwards',
    'Small (>576px) - column hidden on this device and downwards'=>'Small (>576px) - column hidden on this device and downwards',
    
    'Medium (>768px) - no style selected'=>'Medium (>768px) - no style selected',
    'Medium (>768px) - flexbox column'=>'Medium (>768px) - flexbox column',
    'Medium (>768px) - column width: 1/12'=>'Medium (>768px) - column width: 1/12',
    'Medium (>768px) - column width: one sixth'=>'Medium (>768px) - column width: one sixth',
    'Medium (>768px) - column width: one fourth'=>'Medium (>768px) - column width: one fourth',
    'Medium (>768px) - column width: one third'=>'Medium (>768px) - column width: one third',
    'Medium (>768px) - column width: 5/12'=>'Medium (>768px) - column width: 5/12',
    'Medium (>768px) - column width: half'=>'Medium (>768px) - column width: half',
    'Medium (>768px) - column width: 7/12'=>'Medium (>768px) - column width: 7/12',
    'Medium (>768px) - column width: two thirds'=>'Medium (>768px) - column width: two thirds',
    'Medium (>768px) - column width: three fourths'=>'Medium (>768px) - column width: three fourths',
    'Medium (>768px) - column width: five sixths'=>'Medium (>768px) - column width: five sixths',
    'Medium (>768px) - column width: 11/12'=>'Medium (>768px) - column width: 11/12',
    'Medium (>768px) - column width: full width'=>'Medium (>768px) - column width: full width',
    'Medium (>768px) - column hidden on this device'=>'Medium (>768px) - column hidden on this device',
    'Medium (>768px) - column hidden on this device and upwards'=>'Medium (>768px) - column hidden on this device and upwards',
    'Medium (>768px) - column hidden on this device and downwards'=>'Medium (>768px) - column hidden on this device and downwards',
    
     
    'Large (>992px) - no style selected'=>'Large (>992px) - no style selected',
    'Large (>992px) - flexbox column'=>'Large (>992px) - flexbox column',
    'Large (>992px) - column width: 1/12'=>'Large (>992px) - column width: 1/12',
    'Large (>992px) - column width: one sixth'=>'Large (>992px) - column width: one sixth',
    'Large (>992px) - column width: one fourth'=>'Large (>992px) - column width: one fourth',
    'Large (>992px) - column width: one third'=>'Large (>992px) - column width: one third',
    'Large (>992px) - column width: 5/12'=>'Large (>992px) - column width: 5/12',
    'Large (>992px) - column width: half'=>'Large (>992px) - column width: half',
    'Large (>992px) - column width: 7/12'=>'Large (>992px) - column width: 7/12',
    'Large (>992px) - column width: two thirds'=>'Large (>992px) - column width: two thirds',
    'Large (>992px) - column width: three fourths'=>'Large (>992px) - column width: three fourths',
    'Large (>992px) - column width: five sixths'=>'Large (>992px) - column width: five sixths',
    'Large (>992px) - column width: 11/12'=>'Large (>992px) - column width: 11/12',
    'Large (>992px) - column width: full width'=>'Large (>992px) - column width: full width',
    'Large (>992px) - column hidden on this device'=>'Large (>992px) - column hidden on this device',
    'Large (>992px) - column hidden on this device and upwards'=>'Large (>992px) - column hidden on this device and upwards',
    'Large (>992px) - column hidden on this device and downwards'=>'Large (>992px) - column hidden on this device and downwards',   
    
    
    'Extra large (>1200px) - no style selected'=>'Extra large (>1200px) - no style selected',
    'Extra large (>1200px) - flexbox column'=>'Extra large (>1200px) - flexbox column',
    'Extra large (>1200px) - column width: 1/12'=>'Extra large (>1200px) - column width: 1/12',
    'Extra large (>1200px) - column width: one sixth'=>'Extra large (>1200px) - column width: one sixth',
    'Extra large (>1200px) - column width: one fourth'=>'Extra large (>1200px) - column width: one fourth',
    'Extra large (>1200px) - column width: one third'=>'Extra large (>1200px) - column width: one third',
    'Extra large (>1200px) - column width: 5/12'=>'Extra large (>1200px) - column width: 5/12',
    'Extra large (>1200px) - column width: half'=>'Extra large (>1200px) - column width: half',
    'Extra large (>1200px) - column width: 7/12'=>'Extra large (>1200px) - column width: 7/12',
    'Extra large (>1200px) - column width: two thirds'=>'Extra large (>1200px) - column width: two thirds',
    'Extra large (>1200px) - column width: three fourths'=>'Extra large (>1200px) - column width: three fourths',
    'Extra large (>1200px) - column width: five sixths'=>'Extra large (>1200px) - column width: five sixths',
    'Extra large (>1200px) - column width: 11/12'=>'Extra large (>1200px) - column width: 11/12',
    'Extra large (>1200px) - column width: full width'=>'Extra large (>1200px) - column width: full width',
    'Extra large (>1200px) - column hidden on this device'=>'Extra large (>1200px) - column hidden on this device',
   
    'no column order'=>'no column order',
    'use first'=>'use first',
    'use last'=>'use last',
    'order-1'=>'order-1',
    'order-2'=>'order-2',
    'order-3'=>'order-3',
    'order-4'=>'order-4',
    'order-5'=>'order-5',
    'order-6'=>'order-6',
    'order-7'=>'order-7',
    'order-8'=>'order-8',
    'order-9'=>'order-9',
    'order-10'=>'order-10',
    'order-11'=>'order-11',
    'order-12'=>'order-12',
    
    
    'Small (>576px) no column order'=>'Small (>576px) no column order',
    'use first'=>'use first',
    'use last'=>'use last',
    'Small (>576px) order-1'=>'Small (>576px) order-1',
    'Small (>576px) order-2'=>'Small (>576px) order-2',
    'Small (>576px) order-3'=>'Small (>576px) order-3',
    'Small (>576px) order-4'=>'Small (>576px) order-4',
    'Small (>576px) order-5'=>'Small (>576px) order-5',
    'Small (>576px) order-6'=>'Small (>576px) order-6',
    'Small (>576px) order-7'=>'Small (>576px) order-7',
    'Small (>576px) order-8'=>'Small (>576px) order-8',
    'Small (>576px) order-9'=>'Small (>576px) order-9',
    'Small (>576px) order-10'=>'Small (>576px) order-10',
    'Small (>576px) order-11'=>'Small (>576px) order-11',
    'Small (>576px) order-12'=>'Small (>576px) order-12',
    
     
    'Medium (>768px) no column order'=>'Medium (>768px) no column order',
    'use first'=>'use first',
    'use last'=>'use last',
    'Medium (>768px) order-1'=>'Medium (>768px) order-1',
    'Medium (>768px) order-2'=>'Medium (>768px) order-2',
    'Medium (>768px) order-3'=>'Medium (>768px) order-3',
    'Medium (>768px) order-4'=>'Medium (>768px) order-4',
    'Medium (>768px) order-5'=>'Medium (>768px) order-5',
    'Medium (>768px) order-6'=>'Medium (>768px) order-6',
    'Medium (>768px) order-7'=>'Medium (>768px) order-7',
    'Medium (>768px) order-8'=>'Medium (>768px) order-8',
    'Medium (>768px) order-9'=>'Medium (>768px) order-9',
    'Medium (>768px) order-10'=>'Medium (>768px) order-10',
    'Medium (>768px) order-11'=>'Medium (>768px) order-11',
    'Medium (>768px) order-12'=>'Medium (>768px) order-12' ,  
     
    'Large (>992px) no column order'=>'Large (>992px) no column order',
    'use first'=>'use first',
    'use last'=>'use last',
    'Large (>992px) order-1'=>'Large (>992px) order-1',
    'Large (>992px) order-2'=>'Large (>992px) order-2',
    'Large (>992px) order-3'=>'Large (>992px) order-3',
    'Large (>992px) order-4'=>'Large (>992px) order-4',
    'Large (>992px) order-5'=>'Large (>992px) order-5',
    'Large (>992px) order-6'=>'Large (>992px) order-6',
    'Large (>992px) order-7'=>'Large (>992px) order-7',
    'Large (>992px) order-8'=>'Large (>992px) order-8',
    'Large (>992px) order-9'=>'Large (>992px) order-9',
    'Large (>992px) order-10'=>'Large (>992px) order-10',
    'Large (>992px) order-11'=>'Large (>992px) order-11',
    'Large (>992px) order-12'=>'Large (>992px) order-12',   
    
    'Extra large (>1200px) no column order'=>'Extra large (>1200px) no column order',
    'use first'=>'use first',
    'use last'=>'use last',
    'Extra large (>1200px) order-1'=>'Extra large (>1200px) order-1',
    'Extra large (>1200px) order-2'=>'Extra large (>1200px) order-2',
    'Extra large (>1200px) order-3'=>'Extra large (>1200px) order-3',
    'Extra large (>1200px) order-4'=>'Extra large (>1200px) order-4',
    'Extra large (>1200px) order-5'=>'Extra large (>1200px) order-5',
    'Extra large (>1200px) order-6'=>'Extra large (>1200px) order-6',
    'Extra large (>1200px) order-7'=>'Extra large (>1200px) order-7',
    'Extra large (>1200px) order-8'=>'Extra large (>1200px) order-8',
    'Extra large (>1200px) order-9'=>'Extra large (>1200px) order-9',
    'Extra large (>1200px) order-10'=>'Extra large (>1200px) order-10',
    'Extra large (>1200px) order-11'=>'Extra large (>1200px) order-11',
    'Extra large (>1200px) order-12'=>'Extra large (>1200px) order-12',    
    
    'Extra small (<576px) - no margin'=>'Extra small (<576px) - no margin',
    'Extra small (<576px) - left margin'=>'Extra small (<576px) - left margin',
    'Extra small (<576px) - right margin'=>'Extra small (<576px) - right margin',
    'Extra small (<576px) - margin on both sides'=>'Extra small (<576px) - margin on both sides',
    
     
    'Small (>576px) - no margin'=>'Small (>576px) - no margin',
    'Small (>576px) - left margin'=>'Small (>576px) - left margin',
    'Small (>576px) - right margin'=>'Small (>576px) - right margin',
    'Small (>576px) - margin on both sides'=>'Small (>576px) - margin on both sides', 
    
    
    'Medium (>768px) - no margin'=>'Medium (>768px) - no margin',
    'Medium (>768px) - left margin'=>'Medium (>768px) - left margin',
    'Medium (>768px) - right margin'=>'Medium (>768px) - right margin',
    'Medium (>768px) - margin on both sides'=>'Medium (>768px) - margin on both sides', 
    
        
    'Large (>992px) - no margin'=>'Large (>992px) - no margin',
    'Large (>992px) - left margin'=>'Large (>992px) - left margin',
    'Large (>992px) - right margin'=>'Large (>992px) - right margin',
    'Large (>992px) - margin on both sides'=>'Large (>992px) - margin on both sides',
    
        
    'Extra Large (>1200px) - no margin'=>'Extra Large (>1200px) - no margin',
    'Extra Large (>1200px) - left margin'=>'Extra Large (>1200px) - left margin',
    'Extra Large (>1200px) - right margin'=>'Extra Large (>1200px) - right margin',
    'Extra Large (>1200px) - margin on both sides'=>'Extra Large (>1200px) - margin on both sides',    
    
    
    
);
?>