<?php
$content_captions = array(
    'body'=>'<body>',
    'container'=>'container',
    'row'=>'row',
    'column'=>'column',
    'column_bgswitcher'=>'column with background slideshow',   
    'column_fixed_aspect'=>'column with fixed aspect',     
    'custom'=>'custom content',
    'text_image'=>'text & image',	
    'image'=>'image',
    'carousel'=>'carousel',  
    'carousel_slide'=>'carousel slide',
    'carousel_columns'=>'column-based carousel',
    'carousel_column_group'=>'column group',
    'button'=>'button',
    'fixed_aspect_image'=>'fixed aspect image',  
    'facebook_wall'=>'facebook wall',
    'background_video'=>'background video',
    'card'=>'card',
    'card_header'=>'card header',
    'card_footer'=>'card footer',    
    'card_body'=>'card body',
    'card_image'=>'card image',
    'card_bg_image'=>'card background image',
    'card_title'=>'card title & subtitle',
    'preloader'=>'preloader',    
);
?>